language: ruby
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_23734ca30845_key -iv $encrypted_23734ca30845_iv
  -in deploy.enc -out deploy -d
- eval $(ssh-agent)
- chmod 600 deploy
- ssh-add deploy
install:
- sudo add-apt-repository -y ppa:cassou/emacs
- sudo apt-get -qq update
- sudo apt-get -qq -f install
- sudo apt-get -qq install emacs24 emacs24-el
- wget https://github.com/jgm/pandoc/releases/download/1.13.2/pandoc-1.13.2-1-amd64.deb
- sudo dpkg -i pandoc-1.13.2-1-amd64.deb
- wget https://github.com/jcouyang/blog/archive/master.zip
- unzip master.zip "*.md"
script:
- ./import.sh
- ./ci-publish.sh
cache:
  directories:
  - elisp
  - $HOME/.org-timestamps
  apt: true
after_success:
- ./ci-push.sh
