language: ruby
sudo: false
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_23734ca30845_key -iv $encrypted_23734ca30845_iv
  -in deploy.enc -out deploy -d
- eval $(ssh-agent)
- chmod 600 deploy
- ssh-add deploy
addons:
  apt:
    sources:
    - ppa:cassou/emacs
    packages:
    - emacs24
    - emacs24-el
install:
- wget https://github.com/jgm/pandoc/releases/download/1.13.2/pandoc-1.13.2-1-amd64.deb
- sudo dpkg -i pandoc-1.13.2-1-amd64.deb
- curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
- export PATH="/home/travis/.cask/bin:$PATH"
script:
- cask install
- ./preserve_timestamp.sh
- ./import.sh
- ./ci-publish.sh
after_success:
- ./ci-push.sh
