version: "2"

services:
  blog:
    image: jcouyang/emacs
    environment:
      - PORT=3000
    volumes:
      - .:/emacs
      - org-cache:/blog/public/.org-timestamps
    working_dir: /emacs
    command: cask exec emacs --batch -l emacs.el -f org-publish-all

volumes:
  org-cache:
    external: false

