version: 2
jobs:
  build:
    docker:
      - image: jcouyang/orgpress
    steps:
      - add_ssh_keys:
          fingerprints:
            - '61:3b:b7:35:4b:c4:da:25:d9:3e:a0:6c:ea:9e:9c:f1'
      - checkout
      - run: |
          rm -rf public
          git clone git@github.com:jcouyang/blog.git -b gh-pages public
          rm -rf public/*
      - run: emacs --batch -l orgpress.el -f org-publish-all
      - run: |
          cd public
          git config user.email "oyanglulu@gmail.com"
          git config user.name "oyanglulubot"
          git add .
          git commit -m "circle ci publish :ship:"
          git push origin gh-pages -f

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
